### PR TITLE
fix armour calculation - only use max value of armour per location.

### PR DESCRIPTION
**Pull request by aSemy**
Also try and use template for locations to keep things generic. And finally, write a migration.

### CODE REVIEW

**Comment by aSemy** [comment]
Urgh, I need to fix the line indentation.

Also - don't merge this without fixing the download url in `system.json`, there should be a versioned release not a link to master.

**Comment by moo-man** [comment]
I don't think a versioned released is really that valuable? Simply a develop branch with master being the 'release' seems sufficient to me, but I'll cede to you if you want it.

**Comment by aSemy** [comment]
Yeah, versioning releases is important, we should do it, like the other FVTT systems. I think there's a way to set up Github so you can just press a button and it'll automatically tag and release a version? But it's not hard to do manually.

What do you think of the code to fix the armour bug?

**Comment by moo-man** [comment]
Looks fine to me, I'm going to move it to the develop branch while I setup the release

**Pull request merged**
